---
# Requirements:
#   Inventory Example with Variables:
#     Inventory Group:
#       "DC1 Brokers"
#         "vm_vcenter: vcenter.yourdomain.com"
#         "vm_datacenter: DC1"
#     Inventory Hosts:
#       "DC1-BROKER01.yourdomain.com"
#         "vm_name: DC1-BROKER01"
#       "DC1-BROKER02.yourdomain.com"
#         "vm_name: DC1-BROKER02"
#
#    Playbook Variables Examples:
#      connection_port: 5986
#      connection_type: winrm
#      connection_transport: kerberos
#      connection_cert_validation: ignore
#
#    Credentials Variables Examples:
#      WinRM Credentials:
#        winrm_username: winrm@YOURDOMAIN.COM
#        winrm_password: insertpasswordhere
#      vCenter Credentials:
#        vm_vcenter_username" vcenter@yourdomain.com
#        vm_vcenter_password: insertpasswordhere
#
#    Optional Playbook Requirements:
#      Kerberos:
#        For Kerberos to work, you will need to create a '/etc/krb5.conf' file (see example-krb5.conf in Git Repo)
#
#  Known Issues:
#    1: There seems to be some issues when running the Failover checks.
#       The error occurs because of the WinRM users profile.
#       Delete the profile from the Windows Server (cleanly through 'User Prfole Settings').
#       Then log into the machine to initialize the user profile (running a remote command does not seem to be enough).
#
#    2: The 'win_updates' Ansible Module has some known issues where it hangs and times out.
#       Sometimes restarting the play and/or rebooting the inventory host fixes the issue, but not always.
#         ref: https://github.com/ansible-collections/ansible.windows/issues/516

- name: Microsoft RD Broker Server Patching (HA)
  hosts: all
  vars:
    ansible_user: "{{ winrm_username }}"
    ansible_password: "{{ winrm_password }}"
    ansible_port: "{{ connection_port }}"
    ansible_connection: "{{ connection_type }}"
    ansible_winrm_transport: "{{ connection_transport }}"
    ansible_winrm_server_cert_validation: "{{ connection_cert_validation }}"
  gather_facts: false
  serial: 1
  tasks:

    - name: Confirm Ansible can communicate with the hosts to be patched
      include_tasks: tasks/test-communication.yaml

    - name: If required Failover RD Broker Management Server
      include_tasks: tasks/rds/windows-rdbroker-failover.yaml
      args:
        apply:
          become: yes
          become_method: runas
          become_user: "{{ ansible_user }}"

    - name: Install all available windows update
      include_tasks: tasks/patching/windows-update-all.yaml
      vars:
        ansible_winrm_connection_timeout: 1200
        wsus: default

    - name: If required update VMTools
      include_role:
        name: arole_vmware
        tasks_from: vmware-update-tools.yaml
        apply:
          delegate_to: localhost
      vars:
        hostname: "{{ vm_vcenter }}"
        datacenter: "{{ vm_datacenter }}"
        username: "{{ vm_vcenter_username }}"
        password: "{{ vm_vcenter_password }}"
        name: "{{ vm_name }}"
        vm_validate_certs: false
        ansible_connection: local

    - name: Confirm Ansible can communicate with the patched hosts
      include_tasks: tasks/test-communication.yaml