---
- name: Microsoft RD Web Server Patching (HA)
  hosts: all
  gather_facts: false
  serial: 1
  tasks:

    - name: Confirm Ansible can communicate with the hosts to be patched
      include_tasks: tasks/test-communication.yaml
      vars:
        ansible_user: "{{ winrm_username }}"
        ansible_password: "{{ winrm_password }}"
        ansible_port: "{{ connection_port }}"
        ansible_connection: "{{ connection_type }}"
        ansible_winrm_transport: "{{ connection_transport }}"
        ansible_winrm_server_cert_validation: "{{ connection_cert_validation }}"

    - name: Confirm Ansible can load RDWeb
      include_tasks: tasks/test-rdweb-url.yaml

    - name: Disable Real Server
      ansible.builtin.script:
        cmd: kemp_disable_realserver.py --realserverip "{{ kemp_real_server_ip }}" --kempapiurl "{{ kemp_api_url }}" --kempusername "{{ kemp_api_username }}" --kemppassword "{{ kemp_api_password }}"
        executable: /usr/bin/python3
      delegate_to: localhost
      vars:
        kemp_api_url: "{{ lb_api_url }}"
        kemp_api_username: "{{ kemp_username }}"
        kemp_api_password: "{{ kemp_password }}"
        kemp_real_server_ip: "{{ real_server_ip }}"
      register: disable_real_server

    - debug:
        msg: "{{ disable_real_server.stdout_lines }}"

# Re-enable this once a ansible role has been created.
#    - name: Disable Real Server
#      include_role:
#        name: arole_kemp
#        tasks_from: kemp-disable-real-server.yaml
#        apply:
#          delegate_to: localhost
#      vars:
#        kemp_api_url: "{{ kemp_api_url }}"
#        kemp_username: "{{ kemp_username }}"
#        kemp_password: "{{ kemp_password }}"
#        real_server_ip: "{{ real_server_ip }}"

    - name: Install all available windows update
      include_tasks: tasks/windows-update-all.yaml
      vars:
        ansible_user: "{{ winrm_username }}"
        ansible_password: "{{ winrm_password }}"
        ansible_port: "{{ connection_port }}"
        ansible_connection: "{{ connection_type }}"
        ansible_winrm_transport: "{{ connection_transport }}"
        ansible_winrm_server_cert_validation: "{{ connection_cert_validation }}"
        ansible_winrm_operation_timeout_sec: 300
        ansible_winrm_read_timeout_sec: 301
        wsus: default

    - name: If required update VMTools
      include_role:
        name: arole_vmware
        tasks_from: vmware-update-tools.yaml
        apply:
          delegate_to: localhost
      vars:
        hostname: "{{ vm_vcenter }}"
        datacenter: "{{ vm_datacenter }}"
        username: "{{ vm_vcenter_username }}"
        password: "{{ vm_vcenter_password }}"
        name: "{{ vm_name }}"
        vm_validate_certs: false

    - name: Confirm Ansible can communicate with the patched hosts
      include_tasks: tasks/test-communication.yaml
      vars:
        ansible_user: "{{ winrm_username }}"
        ansible_password: "{{ winrm_password }}"
        ansible_port: "{{ connection_port }}"
        ansible_connection: "{{ connection_type }}"
        ansible_winrm_transport: "{{ connection_transport }}"
        ansible_winrm_server_cert_validation: "{{ connection_cert_validation }}"
    
    - name: Confirm Ansible can load RDWeb
      include_tasks: tasks/test-rdweb-url.yaml
      

    - name: Enable Real Server
      ansible.builtin.script:
        cmd: kemp_enable_realserver.py --realserverip "{{ kemp_real_server_ip }}" --kempapiurl "{{ kemp_api_url }}" --kempusername "{{ kemp_api_username }}" --kemppassword "{{ kemp_api_password }}"
        executable: /usr/bin/python3
      delegate_to: localhost
      vars:
        kemp_api_url: "{{ lb_api_url }}"
        kemp_api_username: "{{ kemp_username }}"
        kemp_api_password: "{{ kemp_password }}"
        kemp_real_server_ip: "{{ real_server_ip }}"
      register: enable_real_server

    - debug:
        msg: "{{ enable_real_server.stdout_lines }}"