---
- name: Microsoft RD License Server Patching (HA)
  hosts: all:!localhost
  gather_facts: false
  serial: 1
  tasks:

    - name: Confirm Ansible can communicate with the hosts to be patched
      include_tasks: tasks/test-communication.yaml
      vars:
        ansible_user: "{{ winrm_username }}"
        ansible_password: "{{ winrm_password }}"
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_transport: kerberos
        ansible_winrm_server_cert_validation: ignore

    - name: Install all available windows update
      include_tasks: tasks/windows-update-all.yaml
      vars:
        ansible_user: "{{ winrm_username }}"
        ansible_password: "{{ winrm_password }}"
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_transport: kerberos
        ansible_winrm_server_cert_validation: ignore
        wsus: default

    - name: If required update VMTools
      include_role:
        name: arole_vmware
        tasks_from: vmware-update-tools.yaml
        apply:
          delegate_to: localhost
      vars:
        hostname: "{{ vm_vcenter }}"
        datacenter: "{{ vm_datacenter }}"
        username: "{{ vm_vcenter_username }}"
        password: "{{ vm_vcenter_password }}"
        name: "{{ vm_name }}"
        vm_validate_certs: false

#    - name: If required update VMTools
#      include_role:
#        name: arole_vmware
#        tasks_from: vmware-update-tools.yaml
#      delegate_to: localhost

    - name: Confirm Ansible can communicate with the patched hosts
      include_tasks: tasks/test-communication.yaml
      vars:
        ansible_user: "{{ winrm_username }}"
        ansible_password: "{{ winrm_password }}"
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_transport: kerberos
        ansible_winrm_server_cert_validation: ignore