---
- name: Microsoft RD License Server Patching (HA)
  hosts: all:!localhost
  serial: 1
  vars:
    ansible_port: 5986
    ansible_user: "{{ winrm_username }}"
    ansible_password: "{{ winrm_password }}"
    ansible_winrm_operation_timeout_sec: 300
    ansible_winrm_read_timeout_sec: 310
    wsus: default
    hostname: "{{ vm_vcenter }}"
    datacenter: "{{ vm_datacenter }}"
    username: "{{ vm_vcenter_username }}"
    password: "{{ vm_vcenter_password }}"
    name: "{{ vm_name }}"
  tasks:

    - name: Confirm Ansible can communicate with the hosts to be patched
      include_tasks: tasks/test-communication.yaml

    - name: Install all available windows update
      include_tasks: tasks/windows-update-all.yaml

    - name: If required update VMTools
      include_role:
        name: arole_vmware
        tasks_from: vmware-update-tools.yaml
        apply:
          delegate_to: localhost

#    - name: If required update VMTools
#      include_role:
#        name: arole_vmware
#        tasks_from: vmware-update-tools.yaml
#      delegate_to: localhost

    - name: Confirm Ansible can communicate with the patched hosts
      include_tasks: tasks/test-communication.yaml