---
# This task will patch a Windows device as many times as is required to install all patches listed in the variabe "k>
#
# Required Variable:
#  - {{ kbs_to_install }} : List of KBs that you have approved for installation
#  - {{ wsus }} : This can be one of three options:
#      "default" - this lets the end point decide which update source to use
#      "managed_server" - this lets you select wsus as the update source to use
#      "windows_update" - this lets you select Windows public servers as the update source

- name: Install Windows updates
    win_updates:
      category_names: '*'
      accept_list: "{{ kbs_to_install }}"
      state: installed
      server_selection: "{{ wsus }}"
      reboot: yes
      reboot_timeout: 1200
      log_path: c:\programdata\ansible_patchlog.log
    register: windows_update_result
    until: windows_update_result.changed == false
    retries: 5

- name: Wait for server to come back online
    wait_for_connection:
      delay: 0
      connect_timeout: 5
      sleep: 60
      timeout: 1200
    when: windows_update_result.reboot_required

- name: debug
    debug:
      msg: "{{ windows_update_result }}"
