---
# This task will will check the health of the availability group replicas (needs to be run on active node).
# Target SQLAG.yourdomain.com rather than SQL01.yourdomain.com or SQL02.yourdomain.com

- name: Check to see if Availability Group Replica Node is Healthy
  ansible.windows.win_shell: |
    # Import Required Powershell Modules
      Import-Module SqlServer

    # Initalise Variables
      $SystemHostname = hostname
      $ErrorActionPreference = 'Stop'
      $AvailabilityGroupDatabases = @()
      $AvailabilityGroupReplicas = @()

    # Gather Data
      $AvailabilityGroups = Get-ChildItem "SQLSERVER:\SQL\$($SystemHostName)\Default\AvailabilityGroups"

      ForEach ($AvailabilityGroup in $AvailabilityGroups) {
        $AvailabilityGroupDatabases += Get-ChildItem "SQLSERVER:\SQL\$($SystemHostName)\Default\AvailabilityGroups\$($AvailabilityGroup.name)\AvailabilityDatabases"

        ForEach ($AvailabilityGroupDatabase in $AvailabilityGroupDatabases) {
          $AvailabilityGroupReplicas += Get-ChildItem "SQLSERVER:\SQL\$($SystemHostName)\Default\AvailabilityGroups\$($AvailabilityGroup.name)\AvailabilityReplicas"
          }
      }

      $CurrentHost = $AvailabilityGroupReplicas | where-object {$_.name -eq $SystemHostName}

    # Evaluate Health

      # Determine if Current Replica is Connected
      $HostConnected = $CurrentHost.ConnectionState -eq "connected"

      # Determine if Current Replica is Synchronized
      $HostSynchronized = $CurrentHost.RollupSynchronizationState -eq "Synchronized"

      # Repica Node Health
      if ($HostConnected -and $HostSynchronized) {
        Write-Output $True
        } else {
          $ReplicaNodeStatus = New-Object -TypeName PSObject -Property @{
            Name = $CurrentHost.Name;
            Role = ($CurrentHost.Role | Out-String).trim();
            ConnectionState = ($CurrentHost.ConnectionState | Out-String).trim();
            RollupSynchronizationState = ($CurrentHost.RollupSynchronizationState | Out-String).trim();
            }
          Write-Output $ReplicaNodeStatus | Convertto-json
        }
  register: sql_replica_node_healthy

- name: Fail Ansible Play if SQL Replica Node Health Check Fails
  fail:
    msg:
    - "SQL Replica Node Health Check has Failed."
    - "{{ sql_replica_node_healthy.stdout }}"
  when: sql_replica_node_healthy.stdout | trim != "True"

- name: SQL Replica Node Health Status
  ansible.builtin.debug:
    msg: "SQL Replica Node Health Check on {{ ansible_host }} was Successful"
  when: sql_replica_node_healthy.stdout | trim == "True"