---
# This task will reboot a Windows device and wait for the netlogon service to be running, before moving onto the next task.

- name: Validate that the netlogon service has started, before running the next task
  ansible.windows.win_reboot:
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'