---
# This task will will check the health of the availability group replicas (needs to be run on active node).
# Target SQLAG.yourdomain.com rather than SQL01.yourdomain.com or SQL02.yourdomain.com
# I have hardcoded the SQL Instance 'Default' into these paths, at a future date i would like to pass that as a variable.

- name: SQL Replica Failover Status
  ansible.builtin.debug:
    msg: 
    - "{{ sql_current_replica['sql_availability_groups'] }}"
    - "{{ sql_current_replica['failover_to_node'] }}"

- name: Failover Availability Group
  ansible.windows.win_shell: |
    # Import Required Powershell Modules
      Import-Module SqlServer

    # Initalise Variables
      $ErrorActionPreference = 'Stop'
      $Instance = "{{ item['InstanceName'] }}"
      $FailoverNode = "{{ sql_current_replica['failover_to_node'] }}"
      $AvailabilityGroup = "{{ item['Name'] }}"

    # Failover Availability Group
      $Path = "SQLSERVER:\Sql\$($FailoverNode)\Default\AvailabilityGroups\$($AvailabilityGroup)"
      Switch-SqlAvailabilityGroup -Path $Path
  with_items: "{{ sql_current_replica['sql_availability_groups'] }}"
  delegate_to: "{{ sql_current_replica['failover_to_node_fqdn'] }}"
  register: sql_failover