---
# This task will will check the health of the availability group replicas (needs to be run on active node).
# Target SQLAG.yourdomain.com rather than SQL01.yourdomain.com or SQL02.yourdomain.com
# I have hardcoded the SQL Instance 'Default' into these paths, at a future date i would like to pass that as a variable.

- name: Failover Availability Group
  ansible.windows.win_shell: |
    # Import Required Powershell Modules
      Import-Module SqlServer

    # Initalise Variables
      $SystemHostname = hostname
      $ErrorActionPreference = 'Stop'
      $AvailabilityGroupDatabases = @()
      $AvailabilityGroupReplicas = @()
      $CurrentReplicaStatus = @()
      $AvailabilityGroups = @()
      $Instances = @()

    # Gather Data
      ForEach ($Instance in (Get-ChildItem "SQLSERVER:\SQL\$($SystemHostName)")) {
        $Instances += New-Object -TypeName PSObject -Property @{
          InstanceName = $Instance.DisplayName;
          Version = $Instance.Version;
          ProductLevel = $Instance.ProductLevel;
          UpdateLevel = $Instance.UpdateLevel;
          HostPlatform = $Instance.HostPlatform;
          }
        
        ForEach ($AvailabilityGroup in (Get-ChildItem "SQLSERVER:\SQL\$($SystemHostName)\$($Instance.DisplayName)\AvailabilityGroups")) {
          $AvailabilityGroups += New-Object -TypeName PSObject -Property @{
            Name = $AvailabilityGroup.Name;
            PrimaryReplicaServerName = $AvailabilityGroup.PrimaryReplicaServerName;
            InstanceName = $Instance.DisplayName;
            }

          ForEach ($AvailabilityGroupDatabase in (Get-ChildItem "SQLSERVER:\SQL\$($SystemHostName)\$($Instance.DisplayName)\AvailabilityGroups\$($AvailabilityGroup.name)\AvailabilityDatabases")) {
            $AvailabilityGroupDatabases += New-Object -TypeName PSObject -Property @{
              Name = $AvailabilityGroupDatabase.Name;
              SynchronizationState = $AvailabilityGroupDatabase.SynchronizationState;
              IsSuspended = $AvailabilityGroupDatabase.IsSuspended;
              IsJoined = $AvailabilityGroupDatabase.IsJoined;
              AvailabilityGroup = $AvailabilityGroup.Name;
              InstanceName = $Instance.DisplayName;
              }
            ForEach ($AvailabilityGroupReplica in (Get-ChildItem "SQLSERVER:\SQL\$($SystemHostName)\$($Instance.DisplayName)\AvailabilityGroups\$($AvailabilityGroup.name)\AvailabilityReplicas")) {
              $AvailabilityGroupReplicas += New-Object -TypeName PSObject -Property @{
                Name = $AvailabilityGroupReplica.Name;
                Role = $AvailabilityGroupReplica.Role;
                ConnectionState = $AvailabilityGroupReplica.ConnectionState;
                RollupSynchronizationState = $AvailabilityGroupReplica.RollupSynchronizationState;
                AvailabilityGroup = $AvailabilityGroup.Name;
                InstanceName = $Instance.DisplayName;
                }
              }
            }
          }
        }

      $CurrentHost = $AvailabilityGroupReplicas | where-object {$_.name -eq $systemhostname}
      $FailoverNode = $AvailabilityGroupReplicas | where-object {$_.Role -ne "Primary"}
      $CurrentReplicaStatus = New-Object -TypeName PSObject -Property @{
        Name = $CurrentHost.Name;
        Role = ($CurrentHost.Role | Out-String).trim();
        ConnectionState = ($CurrentHost.ConnectionState | Out-String).trim();
        RollupSynchronizationState = ($CurrentHost.RollupSynchronizationState | Out-String).trim();
        }

    # Determine if Current Replica Role is Primary
      $HostPrimary = $CurrentHost.Role -eq "Primary"

    # Format Results in JSON
          
      $FailoverResults = [PSCustomObject]@{
        failover_required = $HostPrimary
        failover_to_node = $($FailoverNode.Name)
        failover_to_node_fqdn = (Resolve-DNSName $($FailoverNode.Name)).Name
        current_replica_status = $CurrentReplicaStatus
        sql_availability_group_replicas = $AvailabilityGroupReplicas
        sql_availability_group_databases = $AvailabilityGroupDatabases
        sql_availability_groups = $AvailabilityGroups
        sql_instances = $Instances
        }

      $FailoverResults | convertto-json
  register: sql_current_replica

- name: Parse 'sql_current_replica' as JSON and set fact
  set_fact:
    sql_current_replica: "{{ sql_current_replica.stdout | from_json }}"

- name: Fail Ansible Play if SQL Replica Failover Check Fails
  fail:
    msg:
    - "SQL Replica Failover Check on {{ ansible_host }} has Failed."
    - "{{ sql_current_replica['current_replica_status'] }}"
  when: sql_current_replica['failover_required'] | trim != "True" and sql_current_replica['failover_required'] | trim != "False"

- name: SQL Replica Failover Status
  ansible.builtin.debug:
    msg: "SQL Replica Node {{ ansible_host }} Failover is {{ 'Required' if sql_current_replica['failover_required'] | trim == 'True' else 'not Required' }}."