---
# This task will fail the Ansible play if the system does not have sufficient free space to proceed with Windows Updates.
#
# Required Variable:
#  - {{ wsus }} : This can be one of three options:
#      "default" - this lets the end point decide which update source to use
#      "managed_server" - this lets you select wsus as the update source to use
#      "windows_update" - this lets you select Windows public servers as the update source
#
# Notes: The way i had to handle the various patching modes is quite annoying.
# Unfortuntely this is a limitation with how Ansible works, even if a task is skipped, the "register" variable is still recorded.
# This means that i cannot just refer to "windows_update_result" i have to have 3 versions of it for each patching mode.
# This is expected behaviour for Ansible: https://github.com/ansible/ansible/issues/15710.
# This can be managed by using tags, but that added additional execution requirements, and i want to keep this simple.

- name: C Drive Free Space
  ansible.windows.win_shell: |
    $DiskInfo = Get-Volume -DriveLetter "{{ disk_letter }}"
    $Diskinfo | Select-Object DriveLetter,FriendlyName,FileSystem,HealthStatus,Size,SizeRemaining | ConvertTo-JSON
  register: disk_info

- name: Parse JSON and Set Fact
  set_fact:
    disk_info: "{{ disk_info.stdout | from_json }}"

- name: Debug
  ansible.builtin.debug:
    msg: "{{ disk_info }}"

- name: Enough free space on "{{ disk_letter }}" drive to proceed
  ansible.builtin.debug:
    msg: "{{ ansible_host}} has {{ (disk_info.Size | int - disk_info.SizeRemaining | int) | filesizeformat}} free on the {{ disk_letter }} Drive"
  when: (disk_info.Size | int - disk_info.SizeRemaining | int) | filesizeformat >= disk_minimum_free

- name: Fail Ansible Play if there isnt enough free space on "{{ disk_letter }}" drive to proceed
  ansible.builtin.fail:
    msg:
    - "{{ ansible_host}} has {{ (disk_info.Size | int - disk_info.SizeRemaining | int) | filesizeformat}} free on the {{ disk_letter }} Drive"
    - "Not enough free space to proceed."
    - "{{ disk_info }}"
  when:
    - (disk_info.Size | int - disk_info.SizeRemaining | int) | filesizeformat < disk_minimum_free