---
# This task will patch a Windows device as many times as is required to install all available updates"
#
# Required Variable:
#  - {{ wsus }} : This can be one of three options:
#      "default" - this lets the end point decide which update source to use
#      "managed_server" - this lets you select wsus as the update source to use
#      "windows_update" - this lets you select Windows public servers as the update source

- name: Install Windows updates
  ansible.windows.win_updates:
    category_names: '*'
    reject_list: "{{ reject_updates }}"
    server_selection: "{{ wsus }}"
    reboot: yes
    reboot_timeout: 1200
    log_path: c:\programdata\ansible_patchlog.log
  become: yes
  become_method: runas
  become_user: "{{ ansible_user }}"
  register: windows_update_result
  until: windows_update_result.changed == false
  retries: 20
  delay: 60

- name: Wait for server to come back online
  ansible.builtin.wait_for_connection:
    delay: 0
    connect_timeout: 5
    sleep: 60
    timeout: 1200
  when: windows_update_result.reboot_required

- name: debug
  ansible.builtin.debug:
    msg: "{{ windows_update_result }}"
