---
# This task will fail the Ansible play if the system does not have sufficient free space to proceed with Windows Updates.
#
# Required Variable:
#  - {{ disk_minimum_free }} : The free space required to proceed in GB e.g '10'
#  - {{ disk_letter }} : The drive letter to apply the limit to e.g 'C'

- name: C Drive Free Space
  ansible.windows.win_shell: |
    $DiskInfo = Get-Volume -DriveLetter "{{ disk_letter }}"
    $Diskinfo | Select-Object DriveLetter,FriendlyName,FileSystem,HealthStatus,Size,SizeRemaining | ConvertTo-JSON
  register: disk_info

- name: Parse JSON and Set Fact
  set_fact:
    disk_info: "{{ disk_info.stdout | from_json }}"

- name: Debug
  ansible.builtin.debug:
    msg: "{{ disk_info }}"

- name: Enough free space on "{{ disk_letter }}" drive to proceed
  ansible.builtin.debug:
    msg: 
    - "{{ ansible_host }} has {{ disk_info.SizeRemaining | int | filesizeformat }} free on the {{ disk_info.Size | int | filesizeformat }} {{ disk_letter }}: Drive"
    - "{{ disk_info.SizeRemaining | int | filesizeformat }} is {{ ((disk_info.SizeRemaining | int / disk_info.Size | int) * 100) | round }}% free on the {{ disk_letter }} Drive"
  when: (disk_info.SizeRemaining | int) >= (disk_minimum_free | human_to_bytes)

- name: Fail Ansible Play if there isnt enough free space on "{{ disk_letter }}" drive to proceed
  ansible.builtin.fail:
    msg:
    - "{{ ansible_host }} has {{ disk_info.SizeRemaining | int | filesizeformat }} free on the {{ disk_info.Size | int | filesizeformat }} {{ disk_letter }}: Drive"
    - "{{ disk_info.SizeRemaining | int | filesizeformat }} is {{ ((disk_info.SizeRemaining | int / disk_info.Size | int) * 100) | round }}% free on the {{ disk_letter }} Drive"
    - "A minimum of {{ disk_minimum_free }} is required.  Not enough free space to proceed."
    - "{{ disk_info }}"
  when:
    - (disk_info.SizeRemaining | int) < (disk_minimum_free | human_to_bytes)