---
# This task will patch a Windows device as many times as is required to install all patches listed in the variabe "kbs_to_install".

- name: Windows Maintenance
  hosts: all
  vars:
    ansible_user: "{{ winrm_username }}"
    ansible_password: "{{ winrm_password }}"
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Install all available windows update
      include_tasks: tasks/windows-update-specific.yaml