---
# This task will patch a Windows device as many times as is required to install all patches listed in the variabe "kbs_to_install".

- name: Microsoft RD Broker Failover (If Required)
  hosts: all
  vars:
    ansible_user: "{{ winrm_username }}"
    ansible_password: "{{ winrm_password }}"
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  become: yes
  become_method: runas
  tasks:
    - name: If required Failover RD Broker Management Server
      include_tasks: tasks/windows-rdbroker-failover.yaml