---
# This task will patch a Windows device as many times as is required to install all patches listed in the variabe "kbs_to_install".

- name: Windows Maintenance
  hosts: all
  tasks:
    - name: Confirm Ansible can communicate with the hosts to be patched.
      include_tasks: microsoft-windows-ansible/tasks/test-communication.yml
