---
# This task will failover to a different RD Broker (Management Server) in the event that the current host is Active"
# Unofrtunately due to limitations with remotely running the 'Get-RD'

- name: Remove 'AmIActive.json' file if present
  ansible.windows.win_file:
    path: C:\temp\AmIActive.json
    state: absent

- name: Copy Powershell script to "{{ inventory_hostname }}"
  ansible.windows.win_copy:
    src: scripts/rds/windows-rds-broker-active.ps1
    dest: C:\Temp\windows-rds-broker-active.ps1

- name: Create 'AmIActive' Scheduled task
  community.windows.win_scheduled_task:
    name: RDBroker-AmIActive
    username: "{{ winrm_username }}"
    password: "{{ winrm_password }}"
    logon_type: password
    actions:
    - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: -ExecutionPolicy bypass -NonInteractive -NoLogo -File C:\temp\windows-rds-broker-active.ps1
    run_level: highest
    triggers:
    - type: registration
    state: present

- name: Get contents of 'C:\temp\AmIActive.json'
   ansible.windows.win_shell: type C:\temp\AmIActive.json
   register: windows_rdbroker_active

- debug:
    msg: "{{ windows_rdbroker_active.stdout | from_json }}"

- debug:
    msg: "{{ (windows_rdbroker_active.stdout | from_json)['error'] }}"

- name: Fail Ansible Play if RD Broker Server Check Fails
  fail:
    msg: "RD Broker Server Check Failed."
  when: (windows_rdbroker_active.stdout | from_json)['error'] != ""

- name: Create 'AmIActive' Scheduled task
  community.windows.win_scheduled_task:
    name: RDBroker-AmIActive
    state: absent

