---
# This task will failover to a different RD Broker (Management Server) in the event that the current host is Active"

- name: Check to see if Current RD Broker Server is active
  include_tasks: tasks/rds/test-rdbroker-active.yaml
  vars:
    amiactive_runtype: 'before'

- name: Fail Ansible Play if RD Broker Server Check Fails
  fail:
    msg: "RD Broker Server Check Failed."
  when: (windows_rdbroker_before.stdout | from_json)['amiactive'] == "Failed"

#- name: If current RD Broker Server is active, failover
#  ansible.windows.win_shell: |
#    Import-Module RemoteDesktop
#    Function Get-AvailableBroker {
#      $CurrentFQDN = [System.Net.Dns]::GetHostByName($env:computerName).HostName
#      $Brokers = (Get-RDConnectionBrokerHighAvailability).ConnectionBroker
#      $AvailableBrokers = @()
#      foreach ($Broker in ($Brokers | where {$_ -ne $CurrentFQDN})) {
#        $AvailableBrokers += $Broker
#        }
#      Write-Output $AvailableBrokers[0]
#      }
#    
#    Set-RDActiveManagementServer -ManagementServer (Get-AvailableBroker)
#  when: (windows_rdbroker_before.stdout | from_json)['amiactive'] == "True"

- name: Check to see if active RD Broker Server has changed
  include_tasks: tasks/rds/test-rdbroker-active.yaml
  vars:
    amiactive_runtype: 'after'
  args:
    apply:
      until:
        - (windows_rdbroker_after.stdout | from_json)['amiactive'] == "False"
  when: (windows_rdbroker_before.stdout | from_json)['amiactive'] == "True"
  retries: 10
  delay: 30

- name: Fail Ansible Play if RD Broker Server Check Fails
  fail:
    msg: "RD Broker Server Check Failed."
  when:
    - (windows_rdbroker_before.stdout | from_json)['amiactive'] == "True"
    - (windows_rdbroker_after.stdout | from_json)['amiactive'] == "Failed"